# Environment Set Up

In [1]:
import numpy as np
import random

In [2]:
maze = np.zeros((4,4)) # represents a gridworld in which each state, apart from the terminal state, has a value of 0. 
terminal_state = [(0,0), (3,3)]

## Concept Check

What is value? The sum of all future rewards that can be recieved from a given state s. These values are "long lasting. Tells us the long term effects of being in a certain state



## Iterative Policy Evaluation for Gridworld 

What is iterative policy evaluation? Finding the true value function for each state with full knowledge of the environment

In [3]:
# calculate the value of each state given the policy
def policy_eval(maze_values): 
  
    # WHY CAN'T I DO IT. 
                            
    #action = random.randint(0, (1/policy) - 1)
            # 0 = up, 1 = down, 2 = right, 3 = left. maybe put this in a dictionary or something
    # make a for loop for the states:
    
    new_values = maze_values.copy()
    
    for row in range(len(maze_values[0])): 
        for col in range(len(maze_values[1])):
            reward = -1 # -1 for up, down, left, right
            successor_val = 0
            initial_state_val = maze_values[row][col]
            
            if ((row, col) in terminal_state): 
                new_values[row][col] = 0
            else:
                # check left
                if (col - 1 < 0): 
                    successor_val += reward + maze_values[row][col]
                else: 
                    successor_val += (reward + maze_values[row][col - 1])
                # check right
                if (col + 1 >= len(maze_values[1])): 
                    successor_val += reward + maze_values[row][col]
                else: 
                    successor_val += (reward + maze_values[row][col + 1])
                # check up
                if (row - 1 < 0): 
                    successor_val += reward + maze_values[row][col]
                else: 
                    successor_val += (reward + maze_values[row - 1][col])
                # check down
                if (row + 1 >= len(maze_values[0])): 
                    successor_val += reward + maze_values[row][col]
                else: 
                    successor_val += (reward + maze_values[row+1][col])
                
                new_values[row][col] = 0.25 * successor_val
                
            
        
    return np.array(new_values) 
                
            
        
    

                

In [4]:
maze_values = np.zeros((4,4))

print(np.array(maze_values))

current_values = maze_values

for i in range(1000): 
    
    current_values = policy_eval(current_values)
    
    
print(current_values)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]


# MC Prediction

How is MC Prediction different than Iterative Policy Evaluation? We do NOT have full knowledge of the environment. We find the true value function through episodes

What is First Visit Monte Carlo? Averaging returns for a state after the state's first occurence

In [5]:
def step(pos): 
    
    action = random.randint(0,3) # random policy
    successor_val = 0
    successor_state = pos
    reward = -1
    
    if action == 0: # check up
        if not (pos[0] - 1 < 0): 
            successor_state = (pos[0] - 1, pos[1])
    if action == 1: # check down
        if not (pos[0] + 1 > 3): 
            successor_state = (pos[0] + 1, pos[1])
    if action == 2: # check left
        if not (pos[1] - 1 < 0): 
            successor_state = (pos[0], pos[1] - 1)
    if action == 3: # check right
        if not (pos[1] + 1 > 3): 
            successor_state = (pos[0], pos[1] + 1)
    
    if successor_state in terminal_state: 
        reward = 0
        
    if pos in terminal_state:
        reward = 0
                               
    
    return pos, action, reward, successor_state


In [6]:
def first_visit_mc(num_iterations): 
    
    #maze_values = np.zeros((4,4))
    
    from collections import defaultdict
    
    state_rewards = defaultdict(int)
    returns = defaultdict(int)
    all_states = np.array([])
    
    for it in range(1, num_iterations + 1): 
        
        is_terminal = False
        
        initial_state = (random.randint(0,3), random.randint(0,3))
        states_visited = np.array([])
        while not is_terminal:
            initial_state, action, reward, successor_state = step(initial_state)
            states_visited = np.append(states_visited, [initial_state, action, reward, successor_state])
            initial_state = successor_state
            if initial_state in terminal_state: 
                states_visited = np.copy(states_visited.reshape(int(len(states_visited)/4), 4))
                all_states = states_visited
                is_terminal = True
        
    
        for i in range(len(all_states)): 
      
            if all_states[i][0] not in state_rewards.keys(): 
                state_rewards[all_states[i][0]] = np.sum(all_states[i:, 2])
       
        
   
    for state, reward in state_rewards.items(): 
            
        returns[state] = reward / num_iterations
        
        
   
    
    return returns, state_rewards
    
        
    
        
            
            
    # there is still something wrong with this        
            
            
            
    
    
    
    

In [7]:
returns = first_visit_mc(1000)
returns

(defaultdict(int,
             {(0, 3): -0.054,
              (1, 3): -0.052,
              (2, 3): -0.048,
              (2, 2): -0.047,
              (3, 2): -0.046,
              (2, 1): -0.044,
              (3, 1): -0.043,
              (2, 0): -0.038,
              (1, 0): -0.037,
              (1, 1): -0.034,
              (0, 1): -0.033,
              (3, 0): -0.026,
              (1, 2): -0.002,
              (0, 2): -0.001,
              (0, 0): -0.022,
              (3, 3): -0.01}),
 defaultdict(int,
             {(0, 3): -54,
              (1, 3): -52,
              (2, 3): -48,
              (2, 2): -47,
              (3, 2): -46,
              (2, 1): -44,
              (3, 1): -43,
              (2, 0): -38,
              (1, 0): -37,
              (1, 1): -34,
              (0, 1): -33,
              (3, 0): -26,
              (1, 2): -2,
              (0, 2): -1,
              (0, 0): -22,
              (3, 3): -10}))

In [8]:
# construct value grid

maze_values = np.zeros((4,4))

for i in range(maze_values.shape[0]):
    for j in range(maze_values.shape[1]):
        maze_values[i][j] = returns[(i,j)]
print(maze_values)
    


TypeError: tuple indices must be integers or slices, not tuple

In [ ]:
# hold up, why aren't the terminal states 0. hhhh

# MC Control

In [ ]:
def mc_control(num_iterations, discount): 
    
    
    #maze_values = np.zeros((4,4))
    
    from collections import defaultdict
    
    sa_rewards = defaultdict(int)
    returns = defaultdict(int)
    all_states = np.array([])
    sa_visited = defaultdict(int)
    
    for it in range(1, num_iterations + 1): 
        
        is_terminal = False
        
        initial_state = (random.randint(0,3), random.randint(0,3))
        #sa_visited = np.array([])
        while not is_terminal:
            initial_state, action, reward, successor_state = step(initial_state)
            sa = (initial_state, action)
            sa_visited[sa] = reward
            initial_state = successor_state
            if initial_state in terminal_state: 
                #states_visited = np.copy(states_visited.reshape(int(len(states_visited)/4), 4))
                #all_states = states_visited
                is_terminal = True
        
    
        for key, val in sa_visited.items(): 
      
         if sa_visited[key] not in sa_rewards.keys(): 
                sa_rewards[sa_visited[key]] = np.sum(sa_states[i:, 2])
       
        
   
    #for state, reward in state_rewards.items(): 
            
        #returns[state] = reward / num_iterations
        
        
   
    print(sa_visited)
            

            
            
            
            
            
     
